# Generated by Django 4.2.16 on 2024-12-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Riwayat_transaksi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='date',
            new_name='created_at',
        ),
    ]
