# Generated by Django 4.2.16 on 2024-12-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riwayat_transaksi', '0002_rename_date_transactionhistory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='date',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
