# Generated by Django 4.2.16 on 2024-12-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Riwayat_transaksi', '0006_alter_transactionhistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='date',
        ),
    ]
