# Generated by Django 4.2.16 on 2024-12-13 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Riwayat_transaksi', '0008_transactionhistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
