# Generated by Django 4.2.16 on 2024-12-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riwayat_transaksi', '0009_remove_transactionhistory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Dompet Digital', 'Dompet Digital')], default='Cash', max_length=20),
        ),
    ]
