# Generated by Django 4.2.16 on 2024-12-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riwayat_transaksi', '0010_transactionhistory_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Dompet Digital', 'Dompet Digital')], max_length=20),
        ),
    ]
