# Generated by Django 4.2.16 on 2024-12-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riwayat_transaksi', '0013_alter_transactionhistory_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='brand',
            field=models.CharField(default='Unknown Brand', max_length=100),
        ),
    ]
