# Generated by Django 4.2.16 on 2024-12-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riwayat_transaksi', '0014_transactionhistory_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Qris', 'Qris'), ('Transfer Dana', 'Transfer Dana')], default='Cash', max_length=50),
        ),
    ]
