# Generated by Django 4.2.16 on 2024-12-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Riwayat_transaksi', '0016_remove_transactionhistory_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='date',
        ),
    ]
