# Generated by Django 4.2.16 on 2024-12-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riwayat_transaksi', '0017_remove_transactionhistory_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='bukti_transaksi',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_transaksi/'),
        ),
    ]
