# Generated by Django 4.2.16 on 2024-12-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Riwayat_transaksi', '0019_transactionhistory_brand_transactionhistory_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='bukti_transaksi',
        ),
    ]
