# Generated by Django 4.2.16 on 2024-12-15 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Riwayat_transaksi', '0021_remove_transactionhistory_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='brand',
            field=models.CharField(default='Unknown Brand', max_length=100),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Qris', 'Qris'), ('Transfer Dana', 'Transfer Dana')], default='Cash', max_length=50),
        ),
    ]
