# Generated by Django 4.2.16 on 2024-12-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Riwayat_transaksi', '0022_transactionhistory_brand_transactionhistory_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cek', 'Cek'), ('Giro', 'Giro')], default='Cash', max_length=50),
        ),
    ]
