# Generated by Django 4.2.16 on 2024-12-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_list', '0002_alter_perfume_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='name',
        ),
    ]
