# Generated by Django 4.2.16 on 2024-12-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_list', '0006_perfume_name_perfume_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
