# Generated by Django 4.2.16 on 2024-12-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_list', '0008_remove_perfume_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
