# Generated by Django 4.2.16 on 2024-12-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_rename_ordered_date_payment_date_payment_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default='2024-01-01 00:00:00'),
        ),
    ]
