# Generated by Django 4.2.16 on 2024-12-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_payment_payment_method_alter_payment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
    ]
