# Generated by Django 4.2.16 on 2024-12-13 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfume_list', '0007_perfume_is_available_alter_perfume_description_and_more'),
        ('Payment', '0005_alter_payment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='perfume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfume_payments', to='perfume_list.perfume'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
