# Generated by Django 4.2.16 on 2024-12-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0008_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Qris', 'Qris'), ('Transfer Dana', 'Transfer Dana')], default='Cash', max_length=20),
        ),
    ]
