# Generated by Django 4.2.16 on 2024-12-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0011_remove_payment_bukti_transaksi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cek', 'Cek'), ('Giro', 'Giro')], default='Cash', max_length=20),
        ),
    ]
