# Generated by Django 4.2.16 on 2024-12-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kerangka', '0005_perfume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfume',
        ),
    ]
