# Generated by Django 4.2.16 on 2024-12-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kerangka', '0006_delete_perfume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
